apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
data:
  DATABASE_HOST: "POSTGRES_FQDN"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "appdb"
  DATABASE_USER: "pgadmin"
  DATABASE_SSLMODE: "require"
  SERVICE_BUS_NAMESPACE: "SERVICEBUS_NAMESPACE.servicebus.windows.net"
  SERVICE_BUS_QUEUE: "orders"
